[2024-06-20T07:30:32.645+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:30:32.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_regions.run manual__2024-06-20T07:29:25.850609+00:00 [queued]>
[2024-06-20T07:30:32.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_regions.run manual__2024-06-20T07:29:25.850609+00:00 [queued]>
[2024-06-20T07:30:32.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T07:30:33.047+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_regions.run> on 2024-06-20 07:29:25.850609+00:00
[2024-06-20T07:30:33.086+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_regions.run', 'manual__2024-06-20T07:29:25.850609+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2guk4sty']
[2024-06-20T07:30:33.093+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask transform.raw_regions.run
[2024-06-20T07:30:33.086+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=738) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T07:30:33.118+0000] {standard_task_runner.py:63} INFO - Started process 766 to run task
[2024-06-20T07:30:33.184+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T07:30:33.359+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_regions.run manual__2024-06-20T07:29:25.850609+00:00 [running]> on host airflow-scheduler
[2024-06-20T07:30:33.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_regions.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:29:25.850609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:29:25.850609+00:00'
[2024-06-20T07:30:33.965+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:30:33.999+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T07:30:34.004+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp2wn4l0yv from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T07:30:34.045+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T07:30:34.195+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T07:30:34.196+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T07:30:34.199+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T07:30:34.211+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpj1j8gt8x/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T07:30:34.213+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_regions', '--project-dir', '/tmp/tmp2wn4l0yv', '--profiles-dir', '/tmp/tmpj1j8gt8x', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2wn4l0yv
[2024-06-20T07:30:34.230+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:30:34.232+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_regions', '--project-dir', '/tmp/tmp2wn4l0yv', '--profiles-dir', '/tmp/tmpj1j8gt8x', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:30:34.297+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:30:49.608+0000] {subprocess.py:94} INFO - [0m07:30:49  Running with dbt=1.8.2
[2024-06-20T07:30:52.573+0000] {subprocess.py:94} INFO - [0m07:30:52  Registered adapter: snowflake=1.8.3
[2024-06-20T07:30:52.586+0000] {subprocess.py:94} INFO - [0m07:30:52  Encountered an error:
[2024-06-20T07:30:52.588+0000] {subprocess.py:94} INFO - Compilation Error
[2024-06-20T07:30:52.591+0000] {subprocess.py:94} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:30:55.123+0000] {subprocess.py:98} INFO - Command exited with return code 2
[2024-06-20T07:30:55.127+0000] {local.py:254} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:30:56.088+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T07:30:56.091+0000] {local.py:349} INFO - Inlets: []
[2024-06-20T07:30:56.093+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T07:30:56.096+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T07:30:56.218+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T07:30:56.315+0000] {local.py:184} ERROR - [0m07:30:49  Running with dbt=1.8.2
[0m07:30:52  Registered adapter: snowflake=1.8.3
[0m07:30:52  Encountered an error:
Compilation Error
  dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:30:56.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:30:56.362+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 264, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 359, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 185, in handle_exception_subprocess
    raise AirflowException(f"dbt command failed. The command returned a non-zero exit code {result.exit_code}.")
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 2.
[2024-06-20T07:30:56.379+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=transform.raw_regions.run, run_id=manual__2024-06-20T07:29:25.850609+00:00, execution_date=20240620T072925, start_date=20240620T073032, end_date=20240620T073056
[2024-06-20T07:30:56.440+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task transform.raw_regions.run (dbt command failed. The command returned a non-zero exit code 2.; 766)
[2024-06-20T07:30:56.526+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:30:56.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:30:56.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
