[2024-06-17T11:34:57.611+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T11:34:57.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_orders manual__2024-06-17T11:34:51.861717+00:00 [queued]>
[2024-06-17T11:34:57.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_orders manual__2024-06-17T11:34:51.861717+00:00 [queued]>
[2024-06-17T11:34:57.946+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T11:34:58.002+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_process.load_orders> on 2024-06-17 11:34:51.861717+00:00
[2024-06-17T11:34:58.044+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1324) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T11:34:58.057+0000] {standard_task_runner.py:63} INFO - Started process 1353 to run task
[2024-06-17T11:34:58.046+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'load_process.load_orders', 'manual__2024-06-17T11:34:51.861717+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpmzta2uay']
[2024-06-17T11:34:58.082+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask load_process.load_orders
[2024-06-17T11:34:58.164+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T11:34:58.340+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.load_process.load_orders manual__2024-06-17T11:34:51.861717+00:00 [running]> on host airflow-scheduler
[2024-06-17T11:34:58.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='load_process.load_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T11:34:51.861717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T11:34:51.861717+00:00'
[2024-06-17T11:34:58.945+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T11:34:58.948+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-06-17T11:34:58.950+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-17T11:34:58.951+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T11:34:59.289+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T11:34:59.760+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T11:34:59.772+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt.py", line 67, in load
    load_func(df=df, table_names=table)
  File "/local_module/loaders.py", line 34, in load_func
    table_name=table,
               ^^^^^
NameError: name 'table' is not defined. Did you mean: 'tuple'?
[2024-06-17T11:35:00.022+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=load_process.load_orders, run_id=manual__2024-06-17T11:34:51.861717+00:00, execution_date=20240617T113451, start_date=20240617T113457, end_date=20240617T113500
[2024-06-17T11:35:00.113+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task load_process.load_orders (name 'table' is not defined; 1353)
[2024-06-17T11:35:00.145+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T11:35:00.242+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T11:35:00.254+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
